spring:
    # file-service
  jpa:
    properties:
      hibernate.default_schema: ${DB_SCHEMA:file_service}
  application:
    name: ${SERVICE_NAME:file-service-local}

logging:
  level:
    com.netflix.eureka: error
    root: info
